### ISSUE TITLE
Cannot assign null to property Hearth\Components\Checkbox::$checked of type bool

### ISSUE THREAD

**Issue by greatislander** [accessibility-in-action/platform#1403]
**`TypeError`**

Cannot assign null to property Hearth\Components\Checkbox::$checked of type bool

:dart: Hearth\Components\Checkbox::__construct
:page_facing_up: /var/www/html/vendor/fluid-project/hearth/src/Components/Checkbox.php

```php
94   $this->id = $id ?? $this->name;
95   $this->bag = $bag;
96*  $this->checked = $checked;
97   $this->hinted = $hinted;
98   $this->invalid = $this->hasErrors($this->name, $this->bag);
```
[Open in Flare](https://flareapp.io/errors/2516059/latest)

**Comment by jobara** [comment]
I did some tracing back, it appears the issue is that the implementation of `old` will eventually call [`array_key_exists`](https://www.php.net/manual/en/function.array-key-exists.php) which will return `true` if the key in the array exists even if the value is `null`. In this case the [request validation](https://github.com/accessibility-exchange/platform/blob/b0c758bccbd1c85e25f41efa88f5b6cafcc0ac70/app/Http/Requests/UpdateCommunicationAndConsultationPreferencesRequest.php#L64-L78) is explicitly setting the values of `vrs` and `support_person_vrs` to `null`.

**Comment by greatislander** [comment]
That may explain some of those other issues I was having, @jobara— good catch!
