### ISSUE TITLE
Copy Changes from A11y Testing

### ISSUE THREAD

**Issue by michelled** [accessibility-in-action/platform#1419]
General
* On the account settings, make the “Website accessibility” and “access needs” clearly distinct so the user won’t confuse them: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1125%3A21265&t=W4hkkbshaQlPDBJh-1
> Renamed "Access needs" to "Access needs for consultation"

* When adjusting the access needs on the account, provide a description for “meeting in real time”: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1790%3A51698&t=W4hkkbshaQlPDBJh-1

> I also added or edited the description under "for in-person meetings" and "for engagement documents", to make it consistent that each heading has a description.

* On the dashboard, change the label for “Public page” to “My public page” or "My organization's page" if it is published and “Edit my public page” or "Edit my organization's page" if it is not published yet. FRO or comm org members who are not admin only see "My organization's page" if it's published, and they don't see anything if it is not published.

Browse all projects
* Change the reset filters’ button label from “select none” to “clear filters": https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=2478%3A65288&t=W4hkkbshaQlPDBJh-1

Signing up for engagements 
* Provide a description for “intersectional” when confirming details for participating in an engagement: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=4670%3A107062&t=W4hkkbshaQlPDBJh-1
* Update headings when confirming access needs to make it clear 1. they have successfully signed up as per #1191, and 2. they still have to confirm their access needs. https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=3973%3A95155&t=W4hkkbshaQlPDBJh-1

* During the engagement sign up process, add description about what happens if they select yes or no - see above figma link

Projects
* Clarify the labels for “Projects I am participating” and “Projects I am contracted” ( we have not decided on the final phrasing yet) ex for Projects I am contracted: projects I am supporting, organizations I am involved with

> Separate the projects into 3 tabs instead of 2, and naming them:
"Involved as a Consultation Participant"
"Involved as an Accessibility Consultant"
"Involved as a Community Connector"
If the user only has 1 role, don't show any tabs.
If the user only has 1 role currently but previously had another role that still has an active project they're working on, show that tab. (#1161)

* For FROs “Manage project” is not very clear (there’s already an “edit project”) button and user doesn’t link it to a pathway to go to the engagements 
   Make it clear that manage project doesn’t go to editing the project
Instead of "edit project", use "edit project page". Stick to "manage project".

Creating engagements
* When FROs add translation, change the button label to “Add French translation of …”
* When adding time anywhere ex. Creating meetings for an engagement, indicate whether they need to use am/pm or a 24 hour clock (hint text) - https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=2612%3A66872&t=W4hkkbshaQlPDBJh-1
* When creating an engagement, add an explanation for FROs to tell why they can only select one identity criteria - https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=2602%3A65596&t=W4hkkbshaQlPDBJh-1
> The explanation is shown as hint text under the dropdown "type of experiences or identities". I know this page hasn't been developed yet but I'm pretty sure the component has been reused in the selection criteria page.

**Comment by cherylhjli** [comment]
@sepidehshahi for 
> Clarify the labels for “Projects I am participating” and “Projects I am contracted” ( we have not decided on the final phrasing yet) ex for Projects I am contracted: projects I am supporting, organizations I am involved with

What do you think about separating the projects into 3 tabs instead of 2, and naming them:
"Involved as a Consultation Participant"
"Involved as an Accessibility Consultant"
"Involved as a Community Connector"

If someone only has 1 role, then they don't need to have any tabs at all.

**Comment by sepidehshahi** [comment]
I think this is a great idea! Are the tabs generated based on the roles you pick? so if you have selected only one, you won't have tabs. If you have selected two you will have two tabs and if you have chosen all three you will see the three tabs. A question here is that what happens when user edits their role? do we keep the tabs that are not selected anymore?

**Comment by cherylhjli** [comment]
@sepidehshahi re: number of tabs, yes! 
If the user edits their role from, for example, accessibility consultant & consultation participant to just consultation participant, AND they have active projects they are an AC for, they will still see that tab. It's captured in this ticket: https://github.com/accessibility-exchange/platform/issues/1161

**Comment by cherylhjli** [comment]
@chosww @jobara 
This looks great! A few things that I didn't spot the change for:
- When FROs add translation, change the button label to “Add French translation of …” }
new ticket: #1485
- When adding time anywhere ex. Creating meetings for an engagement, indicate whether they need to use am/pm or a 24 hour clock (hint text) - https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=2612%3A66872&t=W4hkkbshaQlPDBJh-
1 new ticket: #1486

And these two should really be another ticket, as they require bigger changes than just copy. I didn't QA them as a part of this PR but the necessary changes should be captured in #1420.
Update headings when confirming access needs to make it clear 1. they have successfully signed up as per

https://github.com/accessibility-exchange/platform/issues/1191, and 2. they still have to confirm their access needs. https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=3973%3A95155&t=W4hkkbshaQlPDBJh-1

During the engagement sign up process, add description about what happens if they select yes or no - see above figma link
