### ISSUE TITLE
Notify Service Org when a Project or Engagement is Deleted

### ISSUE THREAD

**Issue by michelled** [accessibility-in-action/platform#1421]
* Also, include a reason box when deleting a project

**Comment by cherylhjli** [comment]
Deleting engagements when there are no participants signed up yet:
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=5595%3A109220&t=Rjx4EYErtc6fimAO-3
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=5595%3A109186&t=Rjx4EYErtc6fimAO-3

Deleting an engagement with participants already signed up (it's a request instead of an immediate deletion) :
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=5595%3A109230&t=Rjx4EYErtc6fimAO-3
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=5595%3A112222&t=Rjx4EYErtc6fimAO-3

Deleting a project that doesn't have any confirmed participants for any engagements:
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=3001%3A78657&t=Rjx4EYErtc6fimAO-3
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=3001%3A78397&t=Rjx4EYErtc6fimAO-3

Deleting a project that has confirmed participants (a request instead of an immediate deletion):
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=5595%3A109000&t=Rjx4EYErtc6fimAO-3
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=5595%3A110937&t=Rjx4EYErtc6fimAO-3

Delete request shows up on the admin side like so:
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=3099%3A93970&t=Rjx4EYErtc6fimAO-3
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=5595%3A110022&t=Rjx4EYErtc6fimAO-3

Admin should also get an email saying this project has a deletion request, and links it to this page: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=5595%3A110022&t=Rjx4EYErtc6fimAO-3
