### ISSUE TITLE
Signing in and creating an account throws 419 error on staging site

### ISSUE THREAD

**Issue by chosww** [accessibility-in-action/platform#1536]
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**
When signing into the platform, I get 419 error, just with pressing signin button with an empty form. Also, account creation flow is throwing the same error on the second step after the language selection. It seems like an issue with form requests on the platform.

**To Reproduce**

Signin workflow

1. Go to signin page
2. Either enter your account info or without, press sign in
3. see 419 error

Create account workflow

1. Go to signup page
2. Select a main language then press next
3. See 419 error

**Expected behavior**
For login workflow, it should go to the dashboard page, and for the create account flow, it should go to the next step.

**Additional context**
Some of the investigations @gtirloni did: 

- https://infinitbility.medium.com/how-to-solve-the-page-expired-419-error-in-laravel-69fd97b0aa71
- HTTP response status code 419 Page Expired is an unofficial client error that is Laravel-specific and returned by the server to indicate that the Cross-Site Request Forgery (CSRF) validation has failed.

**Comment by jobara** [comment]
While I was able to confirm this issue yesterday morning, by late last night and again today, the issue was no longer reproducible on both the staging and production sites. Will check with CoLab to see if they did anything to rectify the issue.

**Comment by jobara** [comment]
I've put a lengthier description of the situation in the [Fluid General Discussion](https://matrix.to/#/!mDigWuPWilYGiEcOCA:matrix.org/$EEHkYc0AsTuECjNqgoG_ig_uj2azLpxVevDkTFeGfik?via=matrix.org) Matrix channel. The gist is that the issue looks like it resolved itself and we don't have a clear reason for why it happened or why it resolved. CoLab did some experimenting with dropping from 2 pods to 1 pod and moving session storage from the database to a file. This didn't help, but perhaps the process of undoing/restoring things did. Maybe by kicking off some cache clearing or maybe something with the session storage in the database being reset/refreshed. As for the cause, maybe it had something to do with the manual cache clearing that was done after deploy on Thursday. Which we did because the views were cached. This is now part of the deploy process so we should see how things are after deploy and make sure to test login with a few users.

I'm going to close this issue for now and we can either re-open or create a new ticket if we encounter this issue again.

**Comment by jobara** [comment]
Re-opened as we've decided to do further investigation into what may have caused the issue.

**Comment by sbates-idrc** [comment]
Below is a summary of the investigation that was done into this issue. The full notes are available in a Google doc: <https://docs.google.com/document/d/1HMQBR6De3zz3M-Rn2LalGZMevZWCKaMPzn-69pqGHXU/edit?usp=sharing>

# Timeline

- Thursday 2023-02-09 Release v1.0.0-alpha.9
    - Justin successfully logged in with his Admin account for both Staging and Production right after the deploy
    - The team noticed that the views were cached, however, because the new language menu icon wasn't showing up and the sign language video buttons were in the wrong locations. So Marvin cleared the caches for both the staging and production sites.
    - We don't know if anyone tried logging in again after this
- Monday 2023-02-13 4:25pm Daniel was unable to make an account on staging (419)
- Tuesday 2023-02-14 9am No one was able to log in on staging (419)
- Tuesday 2023-02-14 Marvin experimented with changing the storage from database to file and reduced to a single application server
    - Neither of these changes fixed the issue
    - Didn't retest after undoing the changes
    - We believe that by the time Justin checked at approx 11pm, the staging environment was back to database storage and 2 application servers
- Tuesday 2023-02-14 11pm approx Justin able to log into staging and production (Admin account)
- We don't think that anyone checked production during the time that login was failing on staging

# What happens when you visit The Accessibility Exchange and login

- Visit <https://staging.accessibilityexchange.ca/en>
- Two cookies are created:
    - `the_accessibility_exchange_session`
    - `XSRF-TOKEN`
- Visit <https://staging.accessibilityexchange.ca/en/login>
- The login form includes the CSRF token
    - `<input type="hidden" name="_token" value="1vIbOEZYI6XL7BAa3ZhQfpriiDOvWSWldZpS8yVr">`
- Source view page for login: <https://github.com/accessibility-exchange/platform/blob/dev/resources/views/auth/login.blade.php>

The `X-CSRF-TOKEN` header is not being set on the login request (checked using the Firefox Web Developer Tools Network tab) so the `_token` form field value is what is being used (see <https://laravel.com/docs/9.x/csrf#csrf-x-csrf-token>)

If we reload the login page (but don't delete the session cookie), we get the same token:

`<input type="hidden" name="_token" value="1vIbOEZYI6XL7BAa3ZhQfpriiDOvWSWldZpS8yVr">`

If we delete the session cookie and reload the page, we get a different token:

`<input type="hidden" name="_token" value="oAHyURcE0SupvXwujPhFUlV5ozRAYljbNK3IWaNw">`

If we provide bad credentials (such an unknown email address) we see:

- A message at the top of the page "Error Sorry, something went wrong."
- And a message inline in the login form "These credentials do not match our records."

# A way to reproduce the 419 error

We can reproduce the 419 error on the staging site with these steps:

- Change the value of the `_token` form field value using the Firefox Web Developer Tools Inspector
- Click "Sign in" (it isn't necessary to provide an email address or password)

Which I believe means that:

- CSRF token checking happens before the credential check, otherwise we would see a bad credentials response
- The `_token` form field value is what is being checked for CSRF because it was the only thing that was changed

# Sessions and the CSRF token

- User sessions are stored in the `sessions` table in the database
- The CSRF token is generated at creation of the session and stored in the `sessions` table of the database, in the `payload` column, see <https://laravel.com/docs/9.x/csrf> and below
- Sessions expire after a period of inactivity, which is configurable, we are using 120 minutes, see <https://github.com/accessibility-exchange/platform/blob/dev/config/session.php>

# Finding the CSRF token in the `sessions` database table

The session payload, stored in the database, is base 64 encoded and includes the CSRF token as one of the properties.

We can change the welcome blade to include the `@csrf` token and print the session payloads:

```
<form action="">
   @csrf
</form>

<ul>
    @foreach ( DB::table('sessions')->get() as $sessionObj )
        <li> {{ base64_decode($sessionObj->payload) }} </li>
    @endforeach
</ul>
```

Rendered form:

```
<form action="">
    <input type="hidden" name="_token" value="tVdzlImvmEOfRpquCnULuhgWmosPXMA9AVvXul5V">       
 </form>
```

Rendered output of all session payloads, the last one matches the rendered CSRF:

- `a:4:{s:6:"_token";s:40:"YIU4CxdxfPsFTtTVocZrUfv8mBVy1Drg7jyquBIr";s:13:"livewire-urls";a:6:{s:8:"previous";N;s:14:"previous-route";N;s:7:"current";s:23:"http://platform.test/en";s:13:"current-route";s:10:"en.welcome";s:7:"history";a:1:{i:0;s:23:"http://platform.test/en";}s:13:"history-route";a:1:{i:0;s:10:"en.welcome";}}s:9:"_previous";a:1:{s:3:"url";s:23:"http://platform.test/en";}s:6:"_flash";a:2:{s:3:"old";a:0:{}s:3:"new";a:0:{}}}`
- `a:4:{s:6:"_token";s:40:"dGdvIGZJA6cwxEzzifGeCyBeF243DLi9Gh1yYPyW";s:13:"livewire-urls";a:6:{s:8:"previous";s:29:"http://platform.test/en/login";s:14:"previous-route";s:8:"en.login";s:7:"current";s:23:"http://platform.test/en";s:13:"current-route";s:10:"en.welcome";s:7:"history";a:4:{i:0;s:23:"http://platform.test/en";i:1;s:23:"http://platform.test/en";i:2;s:29:"http://platform.test/en/login";i:3;s:23:"http://platform.test/en";}s:13:"history-route";a:4:{i:0;s:10:"en.welcome";i:1;s:10:"en.welcome";i:2;s:8:"en.login";i:3;s:10:"en.welcome";}}s:9:"_previous";a:1:{s:3:"url";s:23:"http://platform.test/en";}s:6:"_flash";a:2:{s:3:"old";a:0:{}s:3:"new";a:0:{}}}`
- `a:4:{s:6:"_token";s:40:"tVdzlImvmEOfRpquCnULuhgWmosPXMA9AVvXul5V";s:13:"livewire-urls";a:6:{s:8:"previous";s:23:"http://platform.test/en";s:14:"previous-route";s:10:"en.welcome";s:7:"current";s:23:"http://platform.test/en";s:13:"current-route";s:10:"en.welcome";s:7:"history";a:12:{i:0;s:23:"http://platform.test/en";i:1;s:23:"http://platform.test/en";i:2;s:23:"http://platform.test/en";i:3;s:23:"http://platform.test/en";i:4;s:23:"http://platform.test/en";i:5;s:23:"http://platform.test/en";i:6;s:23:"http://platform.test/en";i:7;s:23:"http://platform.test/en";i:8;s:23:"http://platform.test/en";i:9;s:23:"http://platform.test/en";i:10;s:23:"http://platform.test/en";i:11;s:23:"http://platform.test/en";}s:13:"history-route";a:12:{i:0;s:10:"en.welcome";i:1;s:10:"en.welcome";i:2;s:10:"en.welcome";i:3;s:10:"en.welcome";i:4;s:10:"en.welcome";i:5;s:10:"en.welcome";i:6;s:10:"en.welcome";i:7;s:10:"en.welcome";i:8;s:10:"en.welcome";i:9;s:10:"en.welcome";i:10;s:10:"en.welcome";i:11;s:10:"en.welcome";}}s:9:"_previous";a:1:{s:3:"url";s:23:"http://platform.test/en";}s:6:"_flash";a:2:{s:3:"old";a:0:{}s:3:"new";a:0:{}}}`

# Potential causes

So far we have been unable to determine what caused the issue. The following are some possibilities:

- A rendered page for one user was cached and shown to a different user
    - CSRF tokens are per session
    - Pages such as the login page contain the CSRF token and are user-specific: at the login page, users already have a session and a CSRF token, though they are not logged in yet
- There was a problem with the session configuration or database access, causing requests to be unable to verify the CSRF token
    - Such as the sessions having already expired by the time the request to log in was received
- Another CSRF token 419 issue was found to be caused by [spatie/laravel-sql-commenter](https://github.com/spatie/laravel-sql-commenter) Is it possible that was involved here also?
    - See https://github.com/accessibility-exchange/platform/issues/1512

**Comment by jobara** [comment]
Closing this as can't duplicate for now as we haven't seen a reoccurrence of the issue yet.
