### ISSUE TITLE
Language modal dialog: No logo

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-in-action/platform#1652]
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**
The page doesn't have the TAE logo.

**Expected behavior**
Please add the logo so the page has the appropriate branding!

**Comment by jobara** [comment]
@cherylhjli Could you please provide some more information about this. I'm not sure what page this is referring or maybe where the logo is missing from.

**Comment by cherylhjli** [comment]
@jobara it's the language picker page: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=7271%3A114883&t=kwjBLUnz6pLiwEjU-1

In the wireframe, there's the white outline TAE logo. On the dev site the logo isn't showing up for me!

**Comment by jobara** [comment]
It appears that this issue is caused by the dark mode theme being on. This can happen when the host system's theme is set to dark mode which will be picked up as the system theme and display the dark theme on the site. The Dark theme currently removes this logo because it usually switches between the regular site logo and the themeable logo.
