### ISSUE TITLE
Public page: Focus area on secondary nav is too big

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-in-action/platform#1690]
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**
Focus area on secondary nav on public pages are too big, and start to encompass the link above and below:
<img width="340" alt="Screenshot 2023-04-27 at 1 00 12 PM" src="https://user-images.githubusercontent.com/9353905/234977567-e20f7be9-5de6-4be2-acf7-a4834004ee2f.png">

This makes it really easy to end up on a link you didn't intend on clicking, and could be a larger barrier for switch users who need to put in a lot more work to click precisely on something.

**Expected behavior**
Have more spacing between the links, like on the project page:
https://staging.accessibilityexchange.ca/en/projects/2

**Comment by sbates-idrc** [comment]
I have experienced this issue when viewing the information for an individual.

If I click on the left hand navigation area ("About", "Experiences", ...) with the mouse pointer over the lower parts of the letters in "About", then the click is registered as being for "Experiences", rather than for "About".
