### ISSUE TITLE
Interview engagement - accepted formats: No error produced when there's no input

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-in-action/platform#1830]
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**
When creating an engagement that's an interview, on the edit engagement page for the accepted formats field, if I don't fill it out it doesn't produce an error. It lets you save, and when I get to requesting an estimate, it doesn't show up on the list of engagements I can get an estimate for.

**To Reproduce**
1. Create an engagement that's an interview
2. Edit engagement
3. Don't fill out the field for accepted formats
4. Save
5. Notice the lack of error message

**Expected behavior**
For this field to be required and produce an error when it's not filled in.

**Comment by jobara** [comment]
There is a validation rule for this in both UpdateEngagementRequest and StoreEngagementRequest. However, it checks `Rule::requiredIf($this->engagement->format === 'interviews' && ! request('other_accepted_format'))`. But `request('other_accepted_format')` always returns an array because it corresponds to a translatable field. It gets something like `['en' => '', 'fr' => '']` even when no input has been entered. We'd actually need to check if any of the values is not empty.
