### ISSUE TITLE
Create local development environment that runs on same container builds as Kube

### ISSUE THREAD

**Issue by marvinroman** [accessibility-in-action/platform#1890]
* Create container builds that are as close as possible to Kube containers.
* Make sure it works across different platforms.

**Comment by colleenskemp** [comment]
Reflecting @marvinroman's email communications in this ticket: I have been using it to test any developments that we have worked on but there is a tedious process of swapping between the development branch and local deployment branch to test that isn't ideal.

Before I am phased out of the project I think it would be helpful to have this merged into the main branches so that testing can be done easier locally. This is the branch I am mentioning -> https://github.com/accessibility-exchange/platform/tree/feat/create-local-dev-environment-that-mirrors-kube

**Comment by colleenskemp** [comment]
@jobara - Any further questions regarding this need/ request?
