### ISSUE TITLE
Fonts fail to load on www subdomain of production site

### ISSUE THREAD

**Issue by jobara** [accessibility-in-action/platform#2006]
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**

The fonts do not load when the site is accessed from the www subdomain. It appears they are trying to be accessed from the root domain and through a CORS error.

**To Reproduce**
1. Go to www.accessibilityexchange.ca
2. Notice the fonts don't appear as expected (compare to https://accessibilityexchange.ca)
3. Open the dev tools 
4. Notice the fonts are trying to be accessed from accessibilityexchange.ca and returning a CORS error

**Expected behavior**

**Screenshots**

<img width="1668" alt="Screenshot shows fonts not loading due to CORS error" src="https://github.com/accessibility-exchange/platform/assets/556024/996c236e-4750-4ef9-96b9-fdbc464c2be2">

**Comment by jobara** [comment]
I couldn't reproduce this in Safari, but have seen it in Firefox and Chrome

**Comment by chosww** [comment]
Not sure how I can test this locally, but we can resolve this issue by adding these lines to .htaccess:

Header add Access-Control-Allow-Origin "*"
Header add Access-Control-Allow-Headers "origin, x-requested-with, content-type"
Header add Access-Control-Allow-Methods "PUT, GET, POST, DELETE, OPTIONS"

Source: https://laracasts.com/discuss/channels/laravel/cors-error-because-of-different-origins

**Comment by jobara** [comment]
The URLs to the fonts are part of the generated Fonts.css file that is create on fetch (`php artisan google-fonts:fetch`).

**Comment by jobara** [comment]
This can be reproduced locally with Herd just by adding a www subdomain in front. For example if the URL is `platform.test` you can use `www.platform.test`.
