### ISSUE TITLE
Enable searching for engagements

### ISSUE THREAD

**Issue by michelled** [accessibility-in-action/platform#2079]
### Is your feature request related to a problem? Please describe.

Consultation participants are able to go to the Browse All Projects page and search for projects but there is no way for them to search for an engagement.

### Describe the solution you'd like

One possible solution is to change the Browse All Projects page to also show and search for engagements.

**Comment by cherylhjli** [comment]
To talk through, cc: @jobara

- As an Individual CP, I interact with engagements. I don’t see projects unless I go to the project page linked from the engagement
    - Search engagements, not projects
    - See engagements I’m involved in, not projects
- As an Individual AC, I interact with engagements. Same as above.
- As an Individual CC, I interact with engagements, Same as above.
- As a CO, I interact with both projects rather than engagements.
    - I see engagements I’m involved in as a CP, AC, or CC
    - I see projects that I’m running 
    - Browse by projects: see what others are doing
    - Question: Do they get to search engagements, or projects, or both?
- As an FRO who is running a project, I interact with projects rather than engagements.
    - Search projects
    - See projects that I’m running
    - Browse by projects: see what others are doing

**Comment by cherylhjli** [comment]
All user types:
- Sees "engagements" in the navigation instead of "projects", which link to the browse all engagements page. On this page users can sort by engagements or projects. The projects view will give them bundles of engagements that are categorized under projects. Projects and engagements are both sorted by most recently published: 
- https://www.figma.com/file/5J9uimqjouSxBJW6JR6uZl/Wireframes---ALL?type=design&node-id=453%3A54457&mode=design&t=R7B4oAupwYvtmZ1J-1
- https://www.figma.com/file/5J9uimqjouSxBJW6JR6uZl/Wireframes---ALL?type=design&node-id=453%3A55866&mode=design&t=R7B4oAupwYvtmZ1J-1
- On this page, add the filter for sign up being open or closed

Individual CP, AC, and CC:
- Have a link on the dashboard called "my engagements", which links to a page that is just engagements they're involved in as an AC/CC/CP
- https://www.figma.com/file/5J9uimqjouSxBJW6JR6uZl/Wireframes---ALL?type=design&node-id=453%3A43930&mode=design&t=R7B4oAupwYvtmZ1J-1

CO:
- Have a link on the dashboard called "my engagements", which links to a page that is just engagements they're involved in as an AC/CC/CP
- Have a link on the dashboard called "projects I'm running", which links to a page that is just projects they have created
- https://www.figma.com/file/5J9uimqjouSxBJW6JR6uZl/Wireframes---ALL?type=design&node-id=1%3A37662&mode=design&t=R7B4oAupwYvtmZ1J-1

FRO:
- Have a link on the dashboard called "projects I'm running", which links to a page that is just projects they have created

Other notes:
- Updated the project card component to have a stronger contrast with the engagement cards, to appear more like a category when the engagements are sorted by projects on the browse all engagements page
- Added "sign up open until.." on the engagement card, and "focus group by [org name]" on engagement cards that are NOT attached to project cards (engagement cards attached to project cards don't need this info as it's on the project card)

Still to do for Cheryl:
- Design the states for the new project cards

**Comment by jobara** [comment]
Additional related work has been filed as #2181 and #2182
