### ISSUE TITLE
Project creation: Team member language question is confusing

### ISSUE THREAD

**Issue by sepidehshahi** [accessibility-in-action/platform#839]

**Comment by cherylhjli** [comment]
@greatislander: @sepidehshahi and I talked and we agreed to remove this field, "Please indicate the language or languages people on your team use fluently."

This is because through testing people were confused as to why this question is being asked. Their expectation is that if a project page is translated to certain languages (ASL, LSQ), that there most likely would also be translation/interpretation available for the actual engagement. This question isn't really adding any additional value or information for someone determining whether they'd want to be involved in a project or engagement - the more important information there is whether their access needs will be met.
