### ISSUE TITLE
Project creation pge: Make URL for training org/trainer website accept more URL formats

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-in-action/platform#885]
currently it only accepts the format "http://"
it produces an error if I type, for example:
- www.google.com
- google.com

**Comment by greatislander** [comment]
@chosww See how this is done here:

https://github.com/accessibility-exchange/platform/blob/775d21032e5867d06ad15a74a6adf868df872644/app/Http/Requests/UpdateIndividualRequest.php#L51-L62

Use the `normalize_url` helper in a `prepareForValidation` method, and use the `active_url` validation rule instead of `url`.
