### ISSUE TITLE
Individual page creation: Add experience button label is confusing

### ISSUE THREAD

**Issue by sepidehshahi** [accessibility-in-action/platform#945]
User assumed that they have to select "Add experience" button to add the information they have entered to their profile. So, they kept adding more fields to their page. Maybe replace with "Add more experiences" or "Add other experiences".

**Comment by cherylhjli** [comment]
How about the button can read "add a relevant experience"?
I think what may also help is putting the fields that show up in a grey 2 background, so that it's more obvious fields have been added: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1766%3A49233
